#!/usr/bin/env zsh
#
# Defines some usefull aliases post-zshrc.
#
# Authors:
#   Markus Hubig <mhubig@gmail.com>
#

alias ls='ls -G'
alias l='ls -alG'
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

if [[ "$OSTYPE" =~ ^darwin ]]; then
    #alias  vim='mvim -p'                     # open in new window
    #alias rvim='mvim -p --remote-tab-silent' # open in existing window

    if [[ -e /usr/local/bin/gdate ]]; then
        alias date='gdate'
    fi
fi

if [[ "$OSTYPE" =~ ^linux  ]]; then
    #alias  vim='gvim -p'                     # open in new window
    #alias rvim='mvim -p --remote-tab-silent' # open in existing window
fi
