#!/usr/bin/env zsh
#
# Defines some usefull functions, post-zshrc.
#
# Authors:
#   Markus Hubig <mhubig@gmail.com>
#

mutt () {
    if (( $# == 1 )) ; then
        command mutt -F ~/.mutt-$1/muttrc
    else
        echo usage: mutt name
    fi
}

# print my public IPv4 Address
ip () {
    command dig +short myip.opendns.com @resolver1.opendns.com
}

# create a scratch file for random notes
scratch () {
    gvim ~/Dropbox\ \(Privat\)/Scratch/$(openssl rand -base64 10 | tr -dc 'a-zA-Z').txt
}

# ssh-copy-id
ssh-copy-id () {

    if (( ! $# )); then
        echo "Usage: $0:t [ssh public key file] user@server.com"
        return 1
    fi

    if [[ $# -eq 1 ]]; then
        command ssh-add -L | ssh $1 "cat - >> ~/.ssh/authorized_keys"
    fi

    if [[ $# -eq 2 ]]; then
        command cat $1 | ssh $2 "cat - >> ~/.ssh/authorized_keys"
    fi
}

# take screenshot from android device
screencap() {
    adb shell screencap -p \
        | perl -pe 's/\x0D\x0A/\x0A/g' \
        > screen-$(date +%s%3N).png
}
